// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using agriApp.Data;

#nullable disable

namespace agriApp.Migrations
{
    [DbContext(typeof(AgriDbContext))]
    [Migration("20251204073859_BuyerInterestLotTable")]
    partial class BuyerInterestLotTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("agriApp.Entities.Auth.JwtToken", b =>
                {
                    b.Property<Guid>("JwtTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccessTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AccessTokenIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AccessTokenJti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DeviceInfo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("RefreshTokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RefreshTokenIssuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("JwtTokenId");

                    b.HasIndex("AccessTokenJti");

                    b.HasIndex("RefreshTokenHash");

                    b.HasIndex("ReplacedByTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("JwtTokens", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Auth.LoginActivity", b =>
                {
                    b.Property<Guid>("ActivityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DeviceInfo")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("IsSuccessful")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LoginTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("ActivityId");

                    b.HasIndex("UserId");

                    b.ToTable("LoginActivities", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Auth.Otp", b =>
                {
                    b.Property<Guid>("OtpId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpireAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("OtpHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OtpId");

                    b.HasIndex("UserId");

                    b.ToTable("Otps", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Auth.UserProfile", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastModificationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("UserProfileId");

                    b.HasIndex("MobileNumber")
                        .IsUnique();

                    b.ToTable("UserProfiles", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Lots.ArrivedLot", b =>
                {
                    b.Property<int>("ArrivedLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArrivedLotId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Grade")
                        .HasColumnType("text");

                    b.Property<string>("LotImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("LotOwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LotOwnerRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MandiId")
                        .HasColumnType("integer");

                    b.Property<Guid>("MandiOfficerId")
                        .HasColumnType("uuid");

                    b.Property<string>("MobileNum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PreLotId")
                        .HasColumnType("text");

                    b.Property<string>("PreRegisteredLotPreLotId")
                        .HasColumnType("character varying(10)");

                    b.Property<string>("QrCodeUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArrivedLotId");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("MandiId");

                    b.HasIndex("MandiOfficerId");

                    b.HasIndex("PreRegisteredLotPreLotId");

                    b.HasIndex("SellerId");

                    b.ToTable("ArrivedLots");
                });

            modelBuilder.Entity("agriApp.Entities.Lots.BuyerInterestLot", b =>
                {
                    b.Property<int>("BuyerInterestLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BuyerInterestLotId"));

                    b.Property<decimal>("BuyerBidAmount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PreLotId")
                        .IsRequired()
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BuyerInterestLotId");

                    b.HasIndex("BuyerId");

                    b.HasIndex("PreLotId", "BuyerId")
                        .IsUnique();

                    b.ToTable("BuyerInterestLots", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Lots.LiveAuctionLot", b =>
                {
                    b.Property<int>("LiveAuctionLotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LiveAuctionLotId"));

                    b.Property<int>("ArrivedLotId")
                        .HasColumnType("integer");

                    b.Property<string>("AuctionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerMobile")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("BuyerName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float?>("FinalPrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LiveAuctionLotId");

                    b.HasIndex("ArrivedLotId");

                    b.HasIndex("AuctionStatus");

                    b.HasIndex("BuyerId");

                    b.ToTable("LiveAuctionLots", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Lots.PreRegisteredLot", b =>
                {
                    b.Property<string>("PreLotId")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpectedArrivalDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LotImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("MandiId")
                        .HasColumnType("integer");

                    b.Property<string>("QrCodeUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<float?>("SellingAmount")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PreLotId");

                    b.HasIndex("CropId");

                    b.HasIndex("FarmerId");

                    b.HasIndex("MandiId");

                    b.HasIndex("SellerId");

                    b.ToTable("PreRegisteredLots", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Market.Crop", b =>
                {
                    b.Property<int>("CropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CropId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CropName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CropId");

                    b.HasIndex("CropName")
                        .IsUnique();

                    b.ToTable("Crops", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Market.Mandi", b =>
                {
                    b.Property<int>("MandiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MandiId"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MandiName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MandiId");

                    b.ToTable("Mandis", (string)null);

                    b.HasData(
                        new
                        {
                            MandiId = 1,
                            Location = "Pune",
                            MandiName = "Pune Marketyard Mandi"
                        },
                        new
                        {
                            MandiId = 2,
                            Location = "Mumbai",
                            MandiName = "Vashi Mandi"
                        },
                        new
                        {
                            MandiId = 3,
                            Location = "Nagpur",
                            MandiName = "Cotton Market"
                        });
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Buyer", b =>
                {
                    b.Property<Guid>("BuyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("BuyerId");

                    b.HasIndex("UserId");

                    b.ToTable("Buyers", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.BuyerInterestedCrop", b =>
                {
                    b.Property<Guid>("BuyerInterestedCropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid");

                    b.Property<int>("CropId")
                        .HasColumnType("integer");

                    b.HasKey("BuyerInterestedCropId");

                    b.HasIndex("BuyerId", "CropId")
                        .IsUnique();

                    b.ToTable("BuyerInterestedCrops", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.FarmDetails", b =>
                {
                    b.Property<Guid>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FarmLocation")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<float>("FarmSize")
                        .HasColumnType("real");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryCrop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FarmId");

                    b.HasIndex("FarmerId");

                    b.ToTable("FarmDetails", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Farmer", b =>
                {
                    b.Property<Guid>("FarmerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FarmerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("FarmerId");

                    b.HasIndex("UserId");

                    b.ToTable("Farmers", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.FarmerInterestedCrop", b =>
                {
                    b.Property<Guid>("FarmerInterestedCropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CropId")
                        .HasColumnType("integer");

                    b.Property<Guid>("FarmerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FarmerInterestedCropId");

                    b.HasIndex("FarmerId", "CropId")
                        .IsUnique();

                    b.ToTable("FarmerInterestedCrops", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.MandiOfficial", b =>
                {
                    b.Property<Guid>("OfficialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmployeeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("MandiId")
                        .HasColumnType("integer");

                    b.Property<string>("OfficialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OfficialRoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("OfficialId");

                    b.HasIndex("MandiId");

                    b.HasIndex("OfficialRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("MandiOfficials", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.OfficialRole", b =>
                {
                    b.Property<Guid>("OfficialRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("OfficialRoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OfficialRoleId");

                    b.ToTable("OfficialRoles", (string)null);

                    b.HasData(
                        new
                        {
                            OfficialRoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            OfficialRoleName = "Mandi Officer",
                            RoleCode = "OFFICER"
                        },
                        new
                        {
                            OfficialRoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            OfficialRoleName = "Mandi Manager",
                            RoleCode = "MANAGER"
                        },
                        new
                        {
                            OfficialRoleId = new Guid("33333333-3333-3333-3333-333333333333"),
                            OfficialRoleName = "Mandi Approver",
                            RoleCode = "APPROVER"
                        });
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Seller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("BusinessName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoUrl")
                        .HasColumnType("text");

                    b.Property<string>("SellerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerId");

                    b.HasIndex("UserId");

                    b.ToTable("Sellers", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.SellerInterestedCrop", b =>
                {
                    b.Property<int>("SellerInterestedCropId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SellerInterestedCropId"));

                    b.Property<int>("CropId")
                        .HasColumnType("integer");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid");

                    b.HasKey("SellerInterestedCropId");

                    b.HasIndex("CropId");

                    b.HasIndex("SellerId", "CropId")
                        .IsUnique();

                    b.ToTable("SellerInterestedCrops", (string)null);
                });

            modelBuilder.Entity("agriApp.Entities.Auth.JwtToken", b =>
                {
                    b.HasOne("agriApp.Entities.Auth.JwtToken", null)
                        .WithMany()
                        .HasForeignKey("ReplacedByTokenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Auth.LoginActivity", b =>
                {
                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Auth.Otp", b =>
                {
                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Lots.ArrivedLot", b =>
                {
                    b.HasOne("agriApp.Entities.Market.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.Farmer", "Farmer")
                        .WithMany()
                        .HasForeignKey("FarmerId");

                    b.HasOne("agriApp.Entities.Market.Mandi", "Mandi")
                        .WithMany()
                        .HasForeignKey("MandiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.MandiOfficial", "MandiOfficer")
                        .WithMany()
                        .HasForeignKey("MandiOfficerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Lots.PreRegisteredLot", "PreRegisteredLot")
                        .WithMany()
                        .HasForeignKey("PreRegisteredLotPreLotId");

                    b.HasOne("agriApp.Entities.Stakeholders.Seller", "Seller")
                        .WithMany()
                        .HasForeignKey("SellerId");

                    b.Navigation("Crop");

                    b.Navigation("Farmer");

                    b.Navigation("Mandi");

                    b.Navigation("MandiOfficer");

                    b.Navigation("PreRegisteredLot");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("agriApp.Entities.Lots.BuyerInterestLot", b =>
                {
                    b.HasOne("agriApp.Entities.Stakeholders.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Lots.PreRegisteredLot", "PreRegisteredLot")
                        .WithMany()
                        .HasForeignKey("PreLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");

                    b.Navigation("PreRegisteredLot");
                });

            modelBuilder.Entity("agriApp.Entities.Lots.LiveAuctionLot", b =>
                {
                    b.HasOne("agriApp.Entities.Lots.ArrivedLot", "ArrivedLot")
                        .WithMany()
                        .HasForeignKey("ArrivedLotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.Buyer", "Buyer")
                        .WithMany()
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ArrivedLot");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("agriApp.Entities.Lots.PreRegisteredLot", b =>
                {
                    b.HasOne("agriApp.Entities.Market.Crop", "Crop")
                        .WithMany("Lots")
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.Farmer", "Farmer")
                        .WithMany("Lots")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("agriApp.Entities.Market.Mandi", "Mandi")
                        .WithMany("Lots")
                        .HasForeignKey("MandiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.Seller", "Seller")
                        .WithMany("Lots")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Crop");

                    b.Navigation("Farmer");

                    b.Navigation("Mandi");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Buyer", b =>
                {
                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.BuyerInterestedCrop", b =>
                {
                    b.HasOne("agriApp.Entities.Stakeholders.Buyer", "Buyer")
                        .WithMany("InterestedCrops")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.FarmDetails", b =>
                {
                    b.HasOne("agriApp.Entities.Stakeholders.Farmer", "Farmer")
                        .WithMany("FarmDetails")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Farmer", b =>
                {
                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.FarmerInterestedCrop", b =>
                {
                    b.HasOne("agriApp.Entities.Stakeholders.Farmer", "Farmer")
                        .WithMany("InterestedCrops")
                        .HasForeignKey("FarmerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farmer");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.MandiOfficial", b =>
                {
                    b.HasOne("agriApp.Entities.Market.Mandi", "Mandi")
                        .WithMany("Officials")
                        .HasForeignKey("MandiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.OfficialRole", "Role")
                        .WithMany("MandiOfficials")
                        .HasForeignKey("OfficialRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mandi");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Seller", b =>
                {
                    b.HasOne("agriApp.Entities.Auth.UserProfile", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.SellerInterestedCrop", b =>
                {
                    b.HasOne("agriApp.Entities.Market.Crop", "Crop")
                        .WithMany()
                        .HasForeignKey("CropId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("agriApp.Entities.Stakeholders.Seller", "Seller")
                        .WithMany("InterestedCrops")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Crop");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("agriApp.Entities.Market.Crop", b =>
                {
                    b.Navigation("Lots");
                });

            modelBuilder.Entity("agriApp.Entities.Market.Mandi", b =>
                {
                    b.Navigation("Lots");

                    b.Navigation("Officials");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Buyer", b =>
                {
                    b.Navigation("InterestedCrops");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Farmer", b =>
                {
                    b.Navigation("FarmDetails");

                    b.Navigation("InterestedCrops");

                    b.Navigation("Lots");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.OfficialRole", b =>
                {
                    b.Navigation("MandiOfficials");
                });

            modelBuilder.Entity("agriApp.Entities.Stakeholders.Seller", b =>
                {
                    b.Navigation("InterestedCrops");

                    b.Navigation("Lots");
                });
#pragma warning restore 612, 618
        }
    }
}
