INSERT INTO "Mandis" ("MandiName", "Location", "District")
VALUES
('Pimpalgaon', '', 'Nashik'),
('Pathardi', '', 'Ahmednagar'),
('Karad', '', 'Satara'),
('Pune(Moshi)', '', 'Pune'),
('Umrane', '', 'Nashik'),
('Laxmi Sopan Agriculture Produce Marketing Co Ltd', '', 'Sholapur'),
('Kopargaon', '', 'Ahmednagar'),
('Nasik', '', 'Nashik'),
('Malkapur', '', 'Buldhana'),
('Parner', '', 'Ahmednagar'),
('Paithan', '', 'Chattrapati Sambhajinagar'),
('Vita', '', 'Sangli'),
('Akluj', '', 'Sholapur'),
('Dindori(Vani)', '', 'Nashik'),
('Yawal', '', 'Jalgaon'),
('Satara', '', 'Satara'),
('Ahmednagar', '', 'Ahmednagar'),
('Jalgaon', '', 'Jalgaon'),
('Vadgaonpeth', '', 'Kolhapur'),
('Satana', '', 'Nashik'),
('Lasur Station', '', 'Chattrapati Sambhajinagar'),
('Khed(Chakan)', '', 'Pune'),
('Nandgaon', '', 'Nashik'),
('Kalyan', '', 'Thane'),
('Karjat(Raigad)', '', 'Raigad'),
('Shevgaon', '', 'Ahmednagar'),
('Karjat', '', 'Ahmednagar'),
('Sangli(Phale, Bhajipura Market)', '', 'Sangli'),
('Navapur', '', 'Nandurbar'),
('Lasalgaon', '', 'Nashik'),
('Mangal Wedha', '', 'Sholapur'),
('Vai', '', 'Satara'),
('Pimpalgaon Baswant(Saykheda)', '', 'Nashik'),
('Indapur', '', 'Pune'),
('Solapur', '', 'Sholapur'),
('Dharashiv', '', 'Dharashiv(Usmanabad)'),
('Dhule', '', 'Dhule'),
('Sakri', '', 'Dhule'),
('Kurdwadi(Modnimb)', '', 'Sholapur'),
('Rahuri(Vambori)', '', 'Ahmednagar'),
('Pune(Khadiki)', '', 'Pune'),
('Kalvan', '', 'Nashik'),
('Lasalgaon(Vinchur)', '', 'Nashik'),
('Vaijpur', '', 'Chattrapati Sambhajinagar'),
('Hingna', '', 'Nagpur'),
('Shree Sairaj Krushi Market', '', 'Ahmednagar'),
('Islampur', '', 'Sangli'),
('Pen', '', 'Raigad'),
('Rahata', '', 'Ahmednagar'),
('Pune(Pimpri)', '', 'Pune'),
('Junnar(Narayangaon)', '', 'Pune'),
('Pune(Manjri)', '', 'Pune'),
('Shrirampur', '', 'Ahmednagar'),
('Malharshree Farmers Producer Co Ltd', '', 'Nashik'),
('Pune', '', 'Pune'),
('Devala', '', 'Nashik'),
('Lonand', '', 'Satara'),
('Manchar', '', 'Pune'),
('Kamthi', '', 'Nagpur'),
('Baramati', '', 'Pune'),
('Bhusaval', '', 'Jalgaon'),
('Sangamner', '', 'Ahmednagar'),
('Jamkhed', '', 'Ahmednagar'),
('Rahuri', '', 'Ahmednagar'),
('Junnar(Otur)', '', 'Pune'),
('Pandharpur', '', 'Sholapur'),
('Chattrapati Sambhajinagar', '', 'Chattrapati Sambhajinagar'),
('Akola', '', 'Akola'),
('Shirpur', '', 'Dhule'),
('Paranda', '', 'Dharashiv(Usmanabad)'),
('Dindori', '', 'Nashik'),
('Amrawati(Frui & Veg. Market)', '', 'Amarawati'),
('Om Chaitanya Multistate Agro Purpose Coop Society', '', 'Ahmednagar'),
('Chandrapur(Ganjwad)', '', 'Chandrapur'),
('Manmad', '', 'Nashik'),
('Akole', '', 'Ahmednagar'),
('Kolhapur', '', 'Kolhapur'),
('Ramtek', '', 'Nagpur'),
('Mankamneshwar Farmar Producer Coltd Sanchalit Mank', '', 'Nashik'),
('Nagpur', '', 'Nagpur'),
('Shree Rameshwar Krushi Market', '', 'Nashik'),
('Nampur', '', 'Nashik'),
('Lasalgaon(Niphad)', '', 'Nashik'),
('Sinner', '', 'Nashik'),
('Newasa(Ghodegaon)', '', 'Ahmednagar'),
('Junnar(Alephata)', '', 'Pune'),
('Chandvad', '', 'Nashik'),
('Gangapur', '', 'Chattrapati Sambhajinagar'),
('Kada', '', 'Beed'),
('Yeola', '', 'Nashik'),
('Junnar', '', 'Pune'),
('Vashi New Mumbai', '', 'Mumbai'),
('Shivsiddha Govind Producer Company Limited Sanchal', '', 'Nashik'),
('Shrigonda', '', 'Ahmednagar');
